export default [
    {
        id: 1,
        city: "Coquitlam",
        title: "Mundy Park",
        description: "Great offleash walking trails as well as a dog park",
        price: 0,
        coverImg: "mundycover.jpg",
        additionalImg: "mundy1.jpg",
        stats: {
            rating: 5.0,
            reviewCount: 18,
            visits: 32
        },
        URL: "https://www.google.com/maps/place/Mundy+Park+Off+Leash+Dog+Park/@49.2524476,-122.8163017,15z/data=!4m2!3m1!1s0x0:0x49e991325243b83a?sa=X&ved=2ahUKEwjnvf7Pxu37AhWgHjQIHQPdDk4Q_BJ6BQiCARAI" ,
        smalldogs: true,
        water: true,
        fence: true,
        offLeashWandering: true,
    },
      {
          id: 2,
          city: "Coquitlam",
          title: "Glen Pine",
          coverImg: "dogswim.jpg",
          description: "Interested in becoming a wedding photographer? For beginner and experienced photographers alike, join us in learning techniques required to leave the happy couple with memories that'll last a lifetime.",
          price: 0,
          coverImg: "glenpine2.jpg",
          additionalImg: "mundy1.jpg",
          stats: {
              rating: 4.2,
              reviewCount: 30,
              visits: 121,
          },
          URL: "https://www.google.com/maps/place/Glen+Park+Off-Leash+Dog+Area/@49.2816454,-122.787408,15z/data=!4m2!3m1!1s0x0:0xb643703b82181da2?sa=X&ved=2ahUKEwiUn6mxx-37AhWaAjQIHc28B2QQ_BJ6BAhvEAg",
          smalldogs: true,
          water: false,
          fence: true,
          offLeashWandering: false,
      },
      {
          id: 3,
          city: "downtown",
          title: "dog swim vancouver",
          description: "Swimming is a great way for your dog to exercise and have fun. We offer a clean, safe and modern alternative to taking your dog down to the beach. We are open all year round so you can treat your dog to a fun swim session no matter what season it is.",
          price: 50,
          coverImg: "dogswim.jpg",
          additionalImg: "mundy1.jpg",
          stats: {
              rating: 4.5,
              reviewCount: 87,
              visits: 0
          },
          URL: "https://www.google.com/search?q=dog+swim+vancouver&rlz=1C1VIQF_enCA992CA992&biw=2133&bih=1004&tbm=lcl&sxsrf=ALiCzsZ9NMnq5F42cbFwMey8fQ8V3sLkng%3A1670624092503&ei=XLOTY4eyHqmO0PEP16WZ-A0&oq=dog+swim&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAMYADIECAAQQzIICAAQgAQQyQMyBQgAEJIDMgUIABCRAjIECAAQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgQIIxAnOgcIABDJAxBDOhAIABCABBCHAhCxAxCDARAUOgoIABCABBCHAhAUOggIABDJAxCRAlAAWOQHYJAPaABwAHgAgAGBAYgBhwWSAQM3LjGYAQCgAQHAAQE&sclient=gws-wiz-local",
          smalldogs: true,
          water: true,
          fence: true,
          offLeashWandering: false,
      },
      {
        id: 4,
        city: "furry creek",
        title: "knob deck trail",
        description: "Swimming is a great way for your dog to exercise and have fun. We offer a clean, safe and modern alternative to taking your dog down to the beach. We are open all year round so you can treat your dog to a fun swim session no matter what season it is.",
        price: 0,
        coverImg: "furrycreek.jpg",
        additionalImg: "mundy1.jpg",
        stats: {
            rating: 10,
            reviewCount: 1,
            visits: 1
        },
        URL: "https://www.alltrails.com/explore/recording/evening-hike-at-furry-creek-knob-deck-trail-798cebc",
        smalldogs: false,
        water: false,
        fence: false,
        offLeashWandering: true,
    },
    {
        id: 5,
        city: "coquitlam",
        title: "lafarge lake",
        description: "The geese poop is frustrating with a puppy.",
        price: 0,
        coverImg: "lafarge.jpg",
        additionalImg: "lafarge1.jpg",
        stats: {
            rating: 3.5,
            reviewCount: 6,
            visits: 6
        },
        URL: "https://www.google.com/maps/place/Lafarge+Lake,+Coquitlam,+BC/data=!4m2!3m1!1s0x54867f3ab0bd1c87:0x80dbe5abad867d41?sa=X&ved=2ahUKEwicgIDhzu37AhXKoFsKHXvkBv0Q8gF6BQiDARAB",
        smalldogs: false,
        water: false,
        fence: false,
        offLeashWandering: false,
    },
    {
        id: 6,
        city: "port coquitlam",
        title: "castle offleash area",
        description: "The off-leash dog park at Castle Park is a large, unfenced grass field.",
        price: 0,
        coverImg: "castlepark.jpg",
        additionalImg: "mundy1.jpg",
        stats: {
            rating: 4.1,
            reviewCount: 1,
            visits: 1
        },
        URL: "https://www.google.com/maps/place/Castle+Park+Off-leash+Dog+Area/@49.2309884,-122.7814515,15z/data=!4m2!3m1!1s0x0:0xba75c33c25a8cadd?sa=X&ved=2ahUKEwj3opaA6Pn7AhXdHzQIHabtARQQ_BJ6BAhzEAg",
        smalldogs: true,
        water: true,
        fence: true,
        offLeashWandering: false,
    },
    {
        id: 6,
        city: "burnaby",
        title: "barnet marine park",
        description: "The off-leash dog park at Castle Park is a large, unfenced grass field.",
        price: 0,
        coverImg: "barnetmarine.jpg",
        stats: {
            rating: 4.9,
            reviewCount: 6,
            visits: 25
        },
        URL: "https://www.google.com/maps/place/Barnet+Marine+Park/@49.2904319,-122.9237377,15z/data=!4m2!3m1!1s0x0:0x2790e0339c216d11?sa=X&ved=2ahUKEwjS8t6d5f77AhXKIzQIHXsXBYwQ_BJ6BQiDARAI",
        smalldogs: false,
        water: true,
        fence: false,
        offLeashWandering: true,
    },
    {
        id: 7,
        city: "burnaby",
        title: "skyline park",
        description: "Located under the power lines, Skyline Dog Park is an unfenced grassy area with a neighbourhood path running through it.",
        price: 0,
        coverImg: "skyline.jpg",
        stats: {
            rating: 0,
            reviewCount: 0,
            visits: 1
        },
        URL: "https://www.google.com/maps/place/Skyline+Park+Off-leash+Dog+Area/@49.2387863,-122.7860322,15z/data=!4m5!3m4!1s0x0:0xa2240ca38f6dd814!8m2!3d49.2387863!4d-122.7860322",
        smalldogs: false,
        water: false,
        fence: false,
        offLeashWandering: false,
    }
]